apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${GATEWAY_API_NAMESPACE}
resources:
  - namespace.yaml
  - github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.2.0
  - https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.15.0/config/crd/gateway/gateway-crds.yaml
  - manifests/gatewayclass.yaml
  - resources/external-gateway.yaml
  - resources/internal-gateway.yaml
helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 1.15.0
    releaseName: aws-load-balancer-controller
    namespace: ${GATEWAY_API_NAMESPACE}
    valuesFile: values.yaml
