clusterName: ${CLUSTER_NAME}
region: ${AWS_REGION}
vpcId: ${VPC_ID}
defaultTargetType: ${GATEWAY_API_CONTROLLER_TARGET_TYPE}
logLevel: ${GATEWAY_API_CONTROLLER_LOG_LEVEL}
enableShield: ${GATEWAY_API_CONTROLLER_ENABLE_SHIELD_ADDON}
enableWaf: ${GATEWAY_API_CONTROLLER_ENABLE_WAF_ADDON}
enableWafv2: ${GATEWAY_API_CONTROLLER_ENABLE_WAFV2_ADDON}
featureGates:
  ALBGatewayAPI: ${GATEWAY_API_CONTROLLER_ENABLE_ALB_GATEWAY}
  NLBGatewayAPI: ${GATEWAY_API_CONTROLLER_ENABLE_NLB_GATEWAY}
defaultTags: ${GATEWAY_API_LOAD_BALANCER_TAGS}
serviceAccount:
  create: true
  name: ${ALB_CONTROLLER_SERVICE_ACCOUNT}
  annotations:
    eks.amazonaws.com/role-arn: ${ALB_CONTROLLER_ROLE_ARN}
