# custom-config.yaml
project:
  name: "devops-autopilot"
  region: "us-east-1"
  bucket: "devops-autopilot-bucket"
  state_key: "devops-autopilot.tfstate"
  dynamodb_table: "devops-autopilot-dynamo-table"
  tags:
    Owner: "Khaled Saidi"
    ManagedBy: "Terraform"
    Environment: "devops-autopilot"

vpc:
  cidr: "10.0.0.0/16"
  enable_ipv6: false
  public_subnet_cidrs:
  - "10.0.1.0/24"
  - "10.0.2.0/24"
  private_subnet_cidrs:
  - "10.0.3.0/24"
  - "10.0.4.0/24"
  add_k8s_tags: true

iam:
  enable_irsa: true
  create_alb_controller_role: true
  lbc_policy_url: "https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.7/docs/install/iam_policy.json"
  alb_controller_namespace: "ingress-system"
  alb_controller_service_account: "aws-load-balancer-controller"
  create_ebs_csi_role: true
  ebs_csi_namespace: "storage-system"
  ebs_csi_service_account: "ebs-csi-controller-sa"
  create_cluster_autoscaler_role: true
  cluster_autoscaler_namespace: "kube-system"
  cluster_autoscaler_service_account: "cluster-autoscaler"
  create_crossplane_core_role: true
  create_crossplane_data_role: true
  crossplane_namespace: "crossplane-system"
  crossplane_core_service_accounts:
  - "provider-aws-core"
  crossplane_data_service_accounts:
  - "provider-aws-data"
  crossplane_core_passrole_arns: []
  crossplane_kms_key_arns: []

eks:
  cluster_name: "devops-autopilot-cluster"
  cluster_user: "khaled"
  version: "1.33"
  generate_kubeconfig: true
  endpoint_private_access: true
  endpoint_public_access: true
  # Leave [] to auto-restrict to caller /32 at apply-time
  public_access_cidrs: []
  service_ipv4_cidr: "172.20.0.0/16"
  enabled_cluster_log_types: [ "api", "audit", "authenticator", "controllerManager", "scheduler" ]

nodegroup:
  # Scaling & shape
  desired_size: 3
  min_size: 2
  max_size: 5
  ami_type: "AL2023_x86_64_STANDARD"
  capacity_type: "ON_DEMAND"
  disk_size: 100
  instance_types: [ "t3.medium" ]
  force_update_version: false
  extra_labels:
    role: "node"
    tier: "app"

  # SSH & Bastion (moved here)
  create_ssh_key: true
  enable_ssh: true
  ssh_key_name: ""
  bastion_instance_type: "t3.micro"
  bastion_ami_id: ""
  bastion_admin_cidrs: []

ansible:
  ansible_enabled: true
  kubectl_version: "v1.34.1"
  helm_version: "v3.19.0"
  dry_run: false
  verbosity: "debug" # one of: quiet, normal, verbose, high, debug
  argocd_namespace: "argocd"
  argocd_create_namespace: true
  argocd_server_service_type: LoadBalancer
  argocd_enable_envsubst_plugin: true
  argocd_enable_lovely_plugin: true
  argocd_wait_timeout: 600
  argocd_wait_interval: 10
  argocd_reconciliation_timeout: "10m"
  argocd_exec_timeout: "600s"

dns:
  base_domain: "kube-forge.com"
  hosted_zone_id: "Z032863786J0OF6PKT1D"

cert_manager:
  email: "khaled.saiidi@outlook.com"
  # server: "https://acme-v02.api.letsencrypt.org/directory"
  server: "https://acme-staging-v02.api.letsencrypt.org/directory"
external_dns:
  txt_owner_id: "devops-autopilot"
  txt_prefix: "_external-dns"
  policy: "sync"
  log_level: "info"
  interval: "1m"
  trigger_loop_on_event: true

gateway_api:
  gateway_class_name: "aws-alb-gateway-class"
  controller:
    default_target_type: "ip"
    enable_alb_gateway: true
    enable_nlb_gateway: false
    enable_shield_addon: false
    log_level: "info"
  load_balancer:
    ip_address_type: "ipv4"
    external_scheme: "internet-facing"
    internal_scheme: "internal"
    deletion_protection_enabled: true
    idle_timeout_seconds: 60
    external_shield_enabled: true
    internal_shield_enabled: false
  external_gateway:
    enabled: true
    name: "public-gateway"
    http_port: 80
    https_port: 443
    allowed_routes_from: "All"
  internal_gateway:
    enabled: true
    name: "internal-gateway"
    http_port: 8080
    https_port: 8443
    allowed_routes_from: "Same"
