# custom-config.yaml
project:
  name: "devops-autopilot"
  region: "us-east-1"
  bucket: "devops-autopilot-bucket"
  state_key: "devops-autopilot.tfstate"
  dynamodb_table: "devops-autopilot-dynamo-table"
  tags:
    Owner: "Khaled Saidi"
    ManagedBy: "Terraform"
    Environment: "devops-autopilot"

vpc:
  cidr: "10.0.0.0/16"
  enable_ipv6: false
  public_subnet_cidrs:
  - "10.0.1.0/24"
  - "10.0.2.0/24"
  private_subnet_cidrs:
  - "10.0.3.0/24"
  - "10.0.4.0/24"
  add_k8s_tags: true

eks:
  cluster_name: "devops-autopilot-cluster"
  cluster_user: "khaled"
  version: "1.33"
  generate_kubeconfig: true
  endpoint_private_access: true
  endpoint_public_access: true
  # Leave [] to auto-restrict to caller /32 at apply-time
  public_access_cidrs: []
  service_ipv4_cidr: "172.20.0.0/16"
  enabled_cluster_log_types: [ "api", "audit", "authenticator", "controllerManager", "scheduler" ]

nodegroup:
  # Scaling & shape
  desired_size: 3
  min_size: 2
  max_size: 5
  ami_type: "AL2_x86_64"
  capacity_type: "ON_DEMAND"
  disk_size: 30
  instance_types: [ "t3.medium" ]
  force_update_version: false
  extra_labels:
    role: "node"
    tier: "app"

  # SSH & Bastion (moved here)
  create_ssh_key: true
  enable_ssh: true
  ssh_key_name: ""
  bastion_instance_type: "t3.micro"
  bastion_ami_id: ""
  bastion_admin_cidrs: []
