apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/platform-project.yaml
  - ../../../base/storage-stack.yaml
  - ../../../base/cert-manager.yaml
  - ../../../base/cni-tuning.yaml
  - ../../../base/cluster-autoscaler.yaml
  - ../../../base/gateway-api.yaml
  - ../../../base/crossplane.yaml
  - ../../../base/external-dns.yaml
  - ../../../base/kyverno.yaml
  - ../../../base/reflector.yaml
  - ../../../base/reloader.yaml
  - ../../../base/vault.yaml
  - ../../../base/external-secrets.yaml
  - ../../../base/databases.yaml
  - ../../../base/harbor.yaml
  - ../../../base/gitlab.yaml
  - ../../../base/zitadel.yaml
  - ../../../base/velero.yaml
  - ../../../base/monitoring.yaml
