apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${CROSSPLANE_NAMESPACE}
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: crossplane-placeholder
    namespace: ${CROSSPLANE_NAMESPACE}
    valuesFile: values.yaml
