apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${CROSSPLANE_CORE_SERVICE_ACCOUNT}
  namespace: ${CROSSPLANE_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${CROSSPLANE_CORE_ROLE_ARN}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${CROSSPLANE_DATA_SERVICE_ACCOUNT}
  namespace: ${CROSSPLANE_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${CROSSPLANE_DATA_ROLE_ARN}
