apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "placeholder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "placeholder.name" . }}
    app.kubernetes.io/managed-by: Helm
data:
  MESSAGE: {{ .Values.app.message | quote }}
