apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/devops-autopilot.git
    targetRevision: main
    path: gitops/apps/cert-manager
    plugin:
      name: argocd-lovely-plugin-v1.0
      env:
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: CERT_MANAGER_NAMESPACE
          value: ${CERT_MANAGER_NAMESPACE}
        - name: CERT_MANAGER_SERVICE_ACCOUNT
          value: ${CERT_MANAGER_SERVICE_ACCOUNT}
        - name: CERT_MANAGER_ROLE_ARN
          value: ${CERT_MANAGER_ROLE_ARN}
        - name: CERT_MANAGER_ISSUER_NAME
          value: ${CERT_MANAGER_ISSUER_NAME}
        - name: CERT_MANAGER_EMAIL
          value: ${CERT_MANAGER_EMAIL}
        - name: CERT_MANAGER_SERVER
          value: ${CERT_MANAGER_SERVER}
        - name: CERT_MANAGER_PRIVATE_KEY_SECRET_NAME
          value: ${CERT_MANAGER_PRIVATE_KEY_SECRET_NAME}
        - name: CERT_MANAGER_EXTERNAL_CERT_SECRET
          value: ${CERT_MANAGER_EXTERNAL_CERT_SECRET}
        - name: CERT_MANAGER_INTERNAL_CERT_SECRET
          value: ${CERT_MANAGER_INTERNAL_CERT_SECRET}
        - name: DNS_HOSTED_ZONE_ID
          value: ${DNS_HOSTED_ZONE_ID}
        - name: DNS_EXTERNAL_WILDCARD
          value: ${DNS_EXTERNAL_WILDCARD}
        - name: DNS_INTERNAL_WILDCARD
          value: ${DNS_INTERNAL_WILDCARD}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${CERT_MANAGER_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
