apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
  labels:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/devops-autopilot.git
    targetRevision: main
    path: gitops/apps/cluster-autoscaler
    plugin:
      env:
        - name: CLUSTER_NAME
          value: ${CLUSTER_NAME}
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: CLUSTER_AUTOSCALER_NAMESPACE
          value: ${CLUSTER_AUTOSCALER_NAMESPACE}
        - name: CLUSTER_AUTOSCALER_SERVICE_ACCOUNT
          value: ${CLUSTER_AUTOSCALER_SERVICE_ACCOUNT}
        - name: CLUSTER_AUTOSCALER_ROLE_ARN
          value: ${CLUSTER_AUTOSCALER_ROLE_ARN}
        - name: NODEGROUP_DESIRED_SIZE
          value: ${NODEGROUP_DESIRED_SIZE}
        - name: NODEGROUP_MIN_SIZE
          value: ${NODEGROUP_MIN_SIZE}
        - name: NODEGROUP_MAX_SIZE
          value: ${NODEGROUP_MAX_SIZE}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${CLUSTER_AUTOSCALER_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
