apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/devops-autopilot.git
    targetRevision: main
    path: gitops/apps/external-secrets
    plugin:
      env:
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: EXTERNAL_SECRETS_NAMESPACE
          value: ${EXTERNAL_SECRETS_NAMESPACE}
        - name: EXTERNAL_SECRETS_SERVICE_ACCOUNT
          value: ${EXTERNAL_SECRETS_SERVICE_ACCOUNT}
        - name: EXTERNAL_SECRETS_ROLE_ARN
          value: ${EXTERNAL_SECRETS_ROLE_ARN}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${EXTERNAL_SECRETS_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
