apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/devops-autopilot.git
    targetRevision: main
    path: gitops/apps/external-dns
    plugin:
      name: argocd-lovely-plugin-v1.0
      env:
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: DNS_ROOT_DOMAIN
          value: ${DNS_ROOT_DOMAIN}
        - name: DNS_BASE_DOMAIN
          value: ${DNS_BASE_DOMAIN}
        - name: DNS_EXTERNAL_LABEL
          value: ${DNS_EXTERNAL_LABEL}
        - name: DNS_INTERNAL_LABEL
          value: ${DNS_INTERNAL_LABEL}
        - name: PROJECT_NAME
          value: ${PROJECT_NAME}
        - name: EXTERNAL_DNS_NAMESPACE
          value: ${EXTERNAL_DNS_NAMESPACE}
        - name: EXTERNAL_DNS_SERVICE_ACCOUNT
          value: ${EXTERNAL_DNS_SERVICE_ACCOUNT}
        - name: EXTERNAL_DNS_ROLE_ARN
          value: ${EXTERNAL_DNS_ROLE_ARN}
        - name: EXTERNAL_DNS_TXT_OWNER_ID
          value: ${EXTERNAL_DNS_TXT_OWNER_ID}
        - name: EXTERNAL_DNS_TXT_PREFIX
          value: ${EXTERNAL_DNS_TXT_PREFIX}
        - name: EXTERNAL_DNS_POLICY
          value: ${EXTERNAL_DNS_POLICY}
        - name: EXTERNAL_DNS_LOG_LEVEL
          value: ${EXTERNAL_DNS_LOG_LEVEL}
        - name: EXTERNAL_DNS_INTERVAL
          value: ${EXTERNAL_DNS_INTERVAL}
        - name: EXTERNAL_DNS_TRIGGER_LOOP_ON_EVENT
          value: ${EXTERNAL_DNS_TRIGGER_LOOP_ON_EVENT}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${EXTERNAL_DNS_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
