apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/devops-autopilot.git
    targetRevision: main
    path: gitops/apps/ingress
    directory:
      recurse: true
    plugin:
      name: envsubst
      env:
      - name: ALB_CONTROLLER_NAMESPACE
        value: ${ALB_CONTROLLER_NAMESPACE}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${ALB_CONTROLLER_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
