apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${CLUSTER_AUTOSCALER_NAMESPACE}
helmCharts:
  - name: cluster-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 9.37.0
    releaseName: cluster-autoscaler
    namespace: ${CLUSTER_AUTOSCALER_NAMESPACE}
    valuesFile: values.yaml
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.1
    releaseName: metrics-server
    namespace: ${CLUSTER_AUTOSCALER_NAMESPACE}
    valuesFile: metrics-server-values.yaml
