nameOverride: cluster-autoscaler
fullnameOverride: cluster-autoscaler
cloudProvider: aws
autoDiscovery:
  enabled: true
  clusterName: ${CLUSTER_NAME}
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/${CLUSTER_NAME}
awsRegion: ${AWS_REGION}
image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.29.1
  pullPolicy: IfNotPresent
rbac:
  create: true
serviceAccount:
  create: true
  name: ${CLUSTER_AUTOSCALER_SERVICE_ACCOUNT}
  annotations:
    eks.amazonaws.com/role-arn: ${CLUSTER_AUTOSCALER_ROLE_ARN}
priorityClassName: system-cluster-critical
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 600Mi
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists
extraArgs:
  balance-similar-node-groups: "true"
  expander: least-waste
  skip-nodes-with-local-storage: "false"
  skip-nodes-with-system-pods: "false"
  scale-down-enabled: "true"
  scale-down-delay-after-add: 1m
  scale-down-delay-after-delete: 1m
  scale-down-delay-after-failure: 30s
  scale-down-unneeded-time: 2m
  scale-down-utilization-threshold: "0.6"
  max-nodes-total: "${NODEGROUP_MAX_SIZE}"
extraEnv:
  - name: AWS_REGION
    value: ${AWS_REGION}
  - name: CLUSTER_AUTOSCALER_NAMESPACE
    value: ${CLUSTER_AUTOSCALER_NAMESPACE}
  - name: NODEGROUP_MIN_SIZE
    value: ${NODEGROUP_MIN_SIZE}
  - name: NODEGROUP_MAX_SIZE
    value: ${NODEGROUP_MAX_SIZE}
  - name: NODEGROUP_DESIRED_SIZE
    value: ${NODEGROUP_DESIRED_SIZE}
