apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: external-secrets-placeholder
    namespace: external-secrets
    valuesFile: values.yaml
