---
- name: Add argo repo
  ansible.builtin.shell: helm repo add argo https://argoproj.github.io/argo-helm && helm repo update
  args: { creates: /tmp/.argo_repo_added }
  register: _repo
- name: Mark repo added
  ansible.builtin.file: { path: /tmp/.argo_repo_added, state: touch }

- name: Install/upgrade Argo CD
  ansible.builtin.shell: |
    helm upgrade --install argocd argo/argo-cd \
      --namespace argocd --create-namespace \
      --set server.service.type=LoadBalancer \
      --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
      --set configs.params.server\.insecure="true" \
      --kubeconfig "{{ kubeconfig_remote_path }}"
  register: argocd_install

- name: Wait for Argo CD API to be Ready
  ansible.builtin.shell: kubectl --kubeconfig "{{ kubeconfig_remote_path }}" -n argocd rollout status deploy/argocd-server --timeout=300s
