- name: Configure Argo CD plugins via ConfigMap
  when: (argocd_enable_envsubst_plugin | bool) or (argocd_enable_lovely_plugin | bool)
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ argocd_kubeconfig }}"
    template: "argocd-cm-plugins.yaml.j2"

- name: Restart repo-server to load plugins
  when: (argocd_enable_envsubst_plugin | bool) or (argocd_enable_lovely_plugin | bool)
  kubernetes.core.k8s:
    state: patched
    kubeconfig: "{{ argocd_kubeconfig }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
        namespace: "{{ argocd_namespace }}"
      spec:
        template:
          metadata:
            annotations:
              rollme.ts: "{{ ansible_date_time.iso8601 }}"
  notify: Wait for repo-server rollout
