apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: reflector-placeholder
    namespace: reflector
    valuesFile: values.yaml
