apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${EXTERNAL_DNS_NAMESPACE}
resources:
  - namespace.yaml
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.15.0
    releaseName: external-dns
    namespace: ${EXTERNAL_DNS_NAMESPACE}
    valuesFile: values.yaml
