apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns-system
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: external-dns-placeholder
    namespace: dns-system
    valuesFile: values.yaml
