provider: aws
txtOwnerId: ${EXTERNAL_DNS_TXT_OWNER_ID}
txtPrefix: ${EXTERNAL_DNS_TXT_PREFIX}
policy: ${EXTERNAL_DNS_POLICY}
logLevel: ${EXTERNAL_DNS_LOG_LEVEL}
interval: ${EXTERNAL_DNS_INTERVAL}
triggerLoopOnEvent: ${EXTERNAL_DNS_TRIGGER_LOOP_ON_EVENT}
env:
  - name: AWS_REGION
    value: ${AWS_REGION}
sources:
  - service
  - ingress
  - gateway-httproute
domainFilters:
  - ${DNS_EXTERNAL_LABEL}.${PROJECT_NAME}.${DNS_BASE_DOMAIN}
  - ${DNS_INTERNAL_LABEL}.${PROJECT_NAME}.${DNS_BASE_DOMAIN}
serviceAccount:
  create: true
  name: ${EXTERNAL_DNS_SERVICE_ACCOUNT}
  annotations:
    eks.amazonaws.com/role-arn: ${EXTERNAL_DNS_ROLE_ARN}
deploymentAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
