apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: reloader-placeholder
    namespace: reloader
    valuesFile: values.yaml
