apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stateful-resources
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: stateful-resources-placeholder
    namespace: stateful-resources
    valuesFile: values.yaml
