apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zitadel
resources:
  - namespace.yaml
helmCharts:
  - name: placeholder
    repo: file://../.charts/placeholder
    releaseName: zitadel-placeholder
    namespace: zitadel
    valuesFile: values.yaml
